/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/machine.glb 
Author: Caio de Oliveira (https://sketchfab.com/caio17011)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pc-gamer-animation-f19fd9e129ba43c09ced9483554aa756
Title: Pc Gamer (Animation)
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function MachineModel(props: any) {

  const group = useRef<THREE.Group>(null!)
  const { nodes, materials, animations } = useGLTF('/models/machine.glb')
  const { actions } = useAnimations(animations, group)

  // Automatically play the first animation if it exists
  useEffect(() => {
    if (actions && Object.keys(actions).length > 0) {
      const firstAction = actions[Object.keys(actions)[0]]
      firstAction?.fadeIn(0.5).play()
    }
  }, [actions])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={9.383}>
          <group name="pcfbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="pCube59" position={[0.009, 6.603, 4.885]} rotation={[0, 0, -2.245]} scale={[1.331, 1.331, 0.719]}>
                  <mesh name="pCube59_pc_modelagem_blinn5_0" geometry={nodes.pCube59_pc_modelagem_blinn5_0.geometry} material={materials.pc_modelagem_blinn5} />
                </group>
                <group name="pCube63" position={[0.009, 7.421, -5.278]} rotation={[0, 0, -2.168]} scale={[1.331, 1.331, 0.719]}>
                  <mesh name="pCube63_pc_modelagem_blinn5_0" geometry={nodes.pCube63_pc_modelagem_blinn5_0.geometry} material={materials.pc_modelagem_blinn5} />
                </group>
                <group name="pCube66" position={[0.009, 5.003, -5.278]} rotation={[0, 0, -2.168]} scale={[1.331, 1.331, 0.719]}>
                  <mesh name="pCube66_pc_modelagem_blinn5_0" geometry={nodes.pCube66_pc_modelagem_blinn5_0.geometry} material={materials.pc_modelagem_blinn5} />
                </group>
                <group name="pCube69" position={[0.009, 2.636, -5.278]} rotation={[0, 0, -2.168]} scale={[1.331, 1.331, 0.719]}>
                  <mesh name="pCube69_pc_modelagem_blinn5_0" geometry={nodes.pCube69_pc_modelagem_blinn5_0.geometry} material={materials.pc_modelagem_blinn5} />
                </group>
                <group name="pCube74" position={[0.853, 4.168, -0.807]} rotation={[0.617, -1.571, 0]} scale={0.725}>
                  <mesh name="pCube74_pc_modelagem_blinn5_0" geometry={nodes.pCube74_pc_modelagem_blinn5_0.geometry} material={materials.pc_modelagem_blinn5} />
                </group>
                <group name="polySurface24" position={[0.162, 7.566, 2.373]} rotation={[-Math.PI, -0.368, -Math.PI]}>
                  <mesh name="polySurface24_pc_modelagem_blinn5_0" geometry={nodes.polySurface24_pc_modelagem_blinn5_0.geometry} material={materials.pc_modelagem_blinn5} />
                </group>
                <group name="polySurface7" position={[0.162, 7.566, -0.208]} rotation={[-Math.PI, -0.368, -Math.PI]}>
                  <mesh name="polySurface7_pc_modelagem_blinn5_0" geometry={nodes.polySurface7_pc_modelagem_blinn5_0.geometry} material={materials.pc_modelagem_blinn5} />
                </group>
                <group name="pCube87" position={[0.853, 4.168, 0.841]} rotation={[2.805, -Math.PI / 2, 0]} scale={0.725}>
                  <mesh name="pCube87_pc_modelagem_blinn5_0" geometry={nodes.pCube87_pc_modelagem_blinn5_0.geometry} material={materials.pc_modelagem_blinn5} />
                </group>
                <group name="pCube88" position={[0.853, 4.168, 2.474]} rotation={[2.805, -Math.PI / 2, 0]} scale={0.725}>
                  <mesh name="pCube88_pc_modelagem_blinn5_0" geometry={nodes.pCube88_pc_modelagem_blinn5_0.geometry} material={materials.pc_modelagem_blinn5} />
                </group>
                <group name="pCube1" position={[0, 4.976, 0]} scale={[4.392, 10.823, 10.434]}>
                  <group name="transform2" />
                </group>
                <group name="pCube2" position={[2.038, 5.046, 0.026]} scale={[7.169, 7.762, 9.902]}>
                  <group name="transform1" />
                </group>
                <group name="pCube3">
                  <group name="transform4" />
                </group>
                <group name="pCube5" position={[0, 5.113, -5.374]} scale={[3.862, 8.509, 0.603]}>
                  <group name="transform6" />
                </group>
                <group name="pCube8" position={[0.115, 6.551, -3.662]} scale={[3.287, 4.38, 2.602]}>
                  <group name="transform3" />
                </group>
                <group name="pCube9" position={[0.038, 6.828, 4.818]} scale={[2.894, 2.894, 1.351]}>
                  <group name="transform16" />
                </group>
                <group name="pCube10" position={[0, 6.685, -3.662]} scale={[3.287, 4.692, 2.602]}>
                  <group name="transform8" />
                </group>
                <group name="pCube11">
                  <group name="transform14" />
                </group>
                <group name="pCube15" position={[0, 5.113, -5.504]} scale={[3, 7.734, 0.916]}>
                  <group name="transform5" />
                </group>
                <group name="pCylinder19" position={[2.48, 4.264, -0.451]} rotation={[0, 0, Math.PI / 2]} scale={[0.848, 0.084, 0.848]}>
                  <group name="transform12" />
                </group>
                <group name="pCube21" position={[0, 6.685, -2.368]} scale={[1.682, 1.16, 1.125]}>
                  <group name="transform7" />
                </group>
                <group name="pCylinder21" position={[2.48, 4.264, 1.374]} rotation={[0, 0, Math.PI / 2]} scale={[0.848, 0.084, 0.848]}>
                  <group name="transform10" />
                </group>
                <group name="pCylinder26" position={[2.48, 4.264, 3.166]} rotation={[0, 0, Math.PI / 2]} scale={[0.848, 0.084, 0.848]}>
                  <group name="transform9" />
                </group>
                <group name="pCube23" position={[2.198, 4.252, 1.378]} scale={[0.606, 2.517, 5.956]}>
                  <group name="transform11" />
                </group>
                <group name="back" position={[0, 0, -1000.1]} rotation={[0, -Math.PI / 2, 0]}>
                  <group name="Object_33" />
                </group>
                <group name="pCylinder27" position={[-2.608, 0.013, -0.395]} scale={[1.349, 0.933, 0.894]}>
                  <group name="transform38" />
                </group>
                <group name="pCylinder34" position={[0.168, 6.6, 5.01]} rotation={[Math.PI / 2, 0, 0]} scale={[1.084, 0.865, 1.084]}>
                  <group name="transform13" />
                </group>
                <group name="pCylinder35" position={[0.168, 6.6, 4.106]} rotation={[Math.PI / 2, 0, 0]} scale={[1.084, 1.842, 1.084]}>
                  <group name="transform15" />
                </group>
                <group name="pCylinder36" position={[0.458, 6.172, -0.112]} rotation={[0, 0, Math.PI / 2]} scale={[0.064, 1.268, 0.121]}>
                  <group name="transform74" />
                </group>
                <group name="pCylinder37" position={[0.168, 6.6, 4.902]} rotation={[Math.PI / 2, 0, 0]} scale={[0.284, 0.056, 0.284]}>
                  <group name="transform30" />
                </group>
                <group name="pCube47" position={[0.901, 6.603, 4.891]} scale={[1, 1, 0.089]}>
                  <group name="transform31" />
                </group>
                <group name="pCylinder38" position={[0.458, 6.3, -0.112]} rotation={[0, 0, Math.PI / 2]} scale={[0.064, 1.268, 0.121]}>
                  <group name="transform72" />
                </group>
                <group name="pCylinder39" position={[0.458, 6.421, -0.112]} rotation={[0, 0, Math.PI / 2]} scale={[0.064, 1.268, 0.121]}>
                  <group name="transform73" />
                </group>
                <group name="pCylinder40" position={[0.458, 6.545, -0.112]} rotation={[0, 0, Math.PI / 2]} scale={[0.064, 1.268, 0.121]}>
                  <group name="transform71" />
                </group>
                <group name="pCylinder41" position={[0.458, 6.671, -0.112]} rotation={[0, 0, Math.PI / 2]} scale={[0.064, 1.268, 0.121]}>
                  <group name="transform70" />
                </group>
                <group name="pCylinder42" position={[0.458, 6.792, -0.112]} rotation={[0, 0, Math.PI / 2]} scale={[0.064, 1.268, 0.121]}>
                  <group name="transform69" />
                </group>
                <group name="pCylinder43" position={[0.458, 7.04, -0.112]} rotation={[0, 0, Math.PI / 2]} scale={[0.064, 1.268, 0.121]}>
                  <group name="transform67" />
                </group>
                <group name="pCylinder44" position={[0.458, 6.914, -0.112]} rotation={[0, 0, Math.PI / 2]} scale={[0.064, 1.268, 0.121]}>
                  <group name="transform68" />
                </group>
                <group name="pCylinder45" position={[0.458, 12.149, -0.112]} rotation={[0, 0, Math.PI / 2]} scale={[0.064, 1.268, 0.121]}>
                  <group name="transform24" />
                </group>
                <group name="pCylinder46" position={[0.458, 12.024, -0.112]} rotation={[0, 0, Math.PI / 2]} scale={[0.064, 1.268, 0.121]}>
                  <group name="transform23" />
                </group>
                <group name="pCylinder47" position={[0.458, 11.901, -0.112]} rotation={[0, 0, Math.PI / 2]} scale={[0.064, 1.268, 0.121]}>
                  <group name="transform22" />
                </group>
                <group name="pCylinder48" position={[0.458, 11.78, -0.112]} rotation={[0, 0, Math.PI / 2]} scale={[0.064, 1.268, 0.121]}>
                  <group name="transform21" />
                </group>
                <group name="pCylinder49" position={[0.458, 11.654, -0.112]} rotation={[0, 0, Math.PI / 2]} scale={[0.064, 1.268, 0.121]}>
                  <group name="transform20" />
                </group>
                <group name="pCylinder50" position={[0.458, 11.53, -0.112]} rotation={[0, 0, Math.PI / 2]} scale={[0.064, 1.268, 0.121]}>
                  <group name="transform19" />
                </group>
                <group name="pCylinder51" position={[0.458, 11.409, -0.112]} rotation={[0, 0, Math.PI / 2]} scale={[0.064, 1.268, 0.121]}>
                  <group name="transform18" />
                </group>
                <group name="pCylinder52" position={[0.458, 11.281, -0.112]} rotation={[0, 0, Math.PI / 2]} scale={[0.064, 1.268, 0.121]}>
                  <group name="transform17" />
                </group>
                <group name="pCylinder54" position={[1.686, 6.172, 1.519]} rotation={[0, 0, Math.PI / 2]} scale={[0.121, 2.112, 0.202]}>
                  <group name="transform26" />
                </group>
                <group name="pCylinder55" position={[1.686, 6.438, 1.519]} rotation={[0, 0, Math.PI / 2]} scale={[0.121, 2.112, 0.202]}>
                  <group name="transform25" />
                </group>
                <group name="pCube52" position={[-0.639, 6.603, 4.891]} rotation={[0, 0, Math.PI]} scale={[1, 1, 0.089]}>
                  <group name="transform29" />
                </group>
                <group name="pCube53" position={[-0.639, 6.603, 14.618]} rotation={[0, 0, Math.PI]} scale={[1, 1, 0.089]}>
                  <group name="transform28" />
                </group>
                <group name="pCube54" position={[0.901, 6.603, 14.618]} scale={[1, 1, 0.089]}>
                  <group name="transform27" />
                </group>
                <group name="pCube55" position={[-4.037, 1.48, -9.727]} rotation={[0, 0, -0.663]}>
                  <group name="transform33" />
                </group>
                <group name="pCube56" position={[-6.252, 4.911, -9.727]} rotation={[0, 0, -1.292]}>
                  <group name="transform35" />
                </group>
                <group name="pCube57" position={[-5.991, 9.079, -9.727]} rotation={[0, 0, -1.935]}>
                  <group name="transform34" />
                </group>
                <group name="pCube58" position={[-3.157, 12.33, -9.727]} rotation={[0, 0, -2.6]}>
                  <group name="transform32" />
                </group>
                <group name="pCube72" position={[4.685, -1.37, -2.827]} scale={[1.331, 1.331, 0.719]}>
                  <group name="transform37" />
                </group>
                <group name="pCylinder60" position={[4.896, 7.417, 0.653]} rotation={[Math.PI / 2, 0, 0]} scale={[0.161, 0.079, 0.153]}>
                  <group name="transform36" />
                </group>
                <group name="pCube75" position={[-5.218, 13.661, -1.15]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.725}>
                  <group name="polySurface15">
                    <group name="transform46" />
                  </group>
                  <group name="polySurface16">
                    <group name="transform53" />
                  </group>
                  <group name="polySurface17">
                    <group name="transform52" />
                  </group>
                  <group name="polySurface18">
                    <group name="transform43" />
                  </group>
                  <group name="polySurface19">
                    <group name="transform51" />
                  </group>
                  <group name="polySurface20">
                    <group name="transform50" />
                  </group>
                  <group name="polySurface21">
                    <group name="transform49" />
                  </group>
                  <group name="polySurface22">
                    <group name="transform44" />
                  </group>
                  <group name="polySurface23">
                    <group name="transform47" />
                  </group>
                  <group name="polySurface24_1">
                    <group name="transform54" />
                  </group>
                  <group name="polySurface25">
                    <group name="transform45" />
                  </group>
                  <group name="polySurface26" position={[-0.021, 0, 0]}>
                    <group name="transform48" />
                  </group>
                  <group name="transform42" />
                </group>
                <group name="pCylinder61" position={[2.89, 3.994, 0.833]} rotation={[0, 0, Math.PI / 2]} scale={[0.808, 0.166, 0.808]}>
                  <group name="transform40" />
                </group>
                <group name="pCylinder62" position={[2.89, 3.994, 0.833]} rotation={[0, 0, Math.PI / 2]} scale={[0.743, 0.607, 0.743]}>
                  <group name="transform39" />
                </group>
                <group name="pCube76" position={[-5.218, 13.661, -3.731]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.725}>
                  <group name="polySurface3">
                    <group name="transform59" />
                  </group>
                  <group name="polySurface4">
                    <group name="transform61" />
                  </group>
                  <group name="polySurface5">
                    <group name="transform60" />
                  </group>
                  <group name="polySurface6">
                    <group name="transform58" />
                  </group>
                  <group name="polySurface7_1">
                    <group name="transform66" />
                  </group>
                  <group name="polySurface8">
                    <group name="transform65" />
                  </group>
                  <group name="polySurface9">
                    <group name="transform62" />
                  </group>
                  <group name="polySurface10">
                    <group name="transform64" />
                  </group>
                  <group name="polySurface11">
                    <group name="transform57" />
                  </group>
                  <group name="polySurface12">
                    <group name="transform56" />
                  </group>
                  <group name="polySurface13">
                    <group name="transform63" />
                  </group>
                  <group name="polySurface14" position={[-0.021, 0, 0]}>
                    <group name="transform55" />
                  </group>
                  <group name="transform41" />
                </group>
                <group name="pc_modelagem_pCube1" position={[0, 4.976, 0]} scale={[4.392, 10.823, 10.434]}>
                  <group name="transform2_1" />
                </group>
                <group name="pc_modelagem_pCube2" position={[2.038, 5.046, 0.026]} scale={[7.169, 7.762, 9.902]}>
                  <group name="transform1_1" />
                </group>
                <group name="pc_modelagem_pCube3">
                  <group name="transform4_1" />
                </group>
                <group name="pCube4" position={[0, 1.988, 1.269]} scale={[3.287, 1.961, 6.994]}>
                  <mesh name="pCube4_lambert36_0" geometry={nodes.pCube4_lambert36_0.geometry} material={materials.lambert36} />
                  <mesh name="pCube4_lambert44_0" geometry={nodes.pCube4_lambert44_0.geometry} material={materials.lambert44} />
                  <mesh name="pCube4_lambert1_0" geometry={nodes.pCube4_lambert1_0.geometry} material={materials.lambert1} />
                  <mesh name="pCube4_lambert45_0" geometry={nodes.pCube4_lambert45_0.geometry} material={materials.lambert45} />
                </group>
                <group name="pc_modelagem_pCube5" position={[0, 5.113, -5.374]} scale={[3.862, 8.509, 0.603]}>
                  <group name="transform6_1" />
                </group>
                <group name="pCube6" position={[-0.55, 6.253, 2.031]} scale={[0.611, 1.434, 1.454]}>
                  <mesh name="pCube6_lambert16_0" geometry={nodes.pCube6_lambert16_0.geometry} material={materials.lambert16} />
                </group>
                <group name="pc_modelagem_pCube8" position={[0.115, 6.551, -3.662]} scale={[3.287, 4.38, 2.602]}>
                  <group name="transform3_1" />
                </group>
                <group name="pc_modelagem_pCube9" position={[0.038, 6.828, 4.818]} scale={[2.894, 2.894, 1.351]}>
                  <group name="transform16_1" />
                </group>
                <group name="pc_modelagem_pCube10" position={[0, 6.685, -3.662]} scale={[3.287, 4.692, 2.602]}>
                  <group name="transform8_1" />
                </group>
                <group name="pc_modelagem_pCube11">
                  <group name="transform14_1" />
                </group>
                <group name="pCube12" position={[0, 8.695, 1.311]} scale={[3.287, 0.593, 7.317]}>
                  <mesh name="pCube12_aiStandardSurface11_0" geometry={nodes.pCube12_aiStandardSurface11_0.geometry} material={materials.aiStandardSurface11} />
                </group>
                <group name="pc_modelagem_pCube15" position={[0, 5.113, -5.504]} scale={[3, 7.734, 0.916]}>
                  <group name="transform5_1" />
                </group>
                <group name="pCube16" position={[0, 0.341, -3.53]} scale={[0.874, 0.933, 0.373]}>
                  <mesh name="pCube16_pc_modelagem_lambert11_0" geometry={nodes.pCube16_pc_modelagem_lambert11_0.geometry} material={materials.pc_modelagem_lambert11} />
                </group>
                <group name="pCube17" position={[-0.07, 5.238, -5.515]} scale={[2.668, 7.556, 0.055]}>
                  <mesh name="pCube17_aiStandardSurface4_0" geometry={nodes.pCube17_aiStandardSurface4_0.geometry} material={materials.aiStandardSurface4} />
                </group>
                <group name="pCylinder6" position={[-0.704, 8.165, -1.145]} scale={[0.096, 0.417, 0.096]}>
                  <mesh name="pCylinder6_pc_modelagem_lambert7_0" geometry={nodes.pCylinder6_pc_modelagem_lambert7_0.geometry} material={materials.pc_modelagem_lambert7} />
                </group>
                <group name="pCylinder7" position={[-0.704, 8.165, 0.702]} scale={[0.096, 0.417, 0.096]}>
                  <mesh name="pCylinder7_pc_modelagem_lambert7_0" geometry={nodes.pCylinder7_pc_modelagem_lambert7_0.geometry} material={materials.pc_modelagem_lambert7} />
                </group>
                <group name="pCylinder8" position={[1.009, 8.165, 0.702]} scale={[0.096, 0.417, 0.096]}>
                  <mesh name="pCylinder8_pc_modelagem_lambert7_0" geometry={nodes.pCylinder8_pc_modelagem_lambert7_0.geometry} material={materials.pc_modelagem_lambert7} />
                </group>
                <group name="pCylinder9" position={[0.168, 8.129, -0.212]} scale={[1.084, 0.331, 1.084]}>
                  <mesh name="pCylinder9_lambert35_0" geometry={nodes.pCylinder9_lambert35_0.geometry} material={materials.lambert35} />
                </group>
                <group name="pCylinder10" position={[1.009, 8.165, -1.145]} scale={[0.096, 0.417, 0.096]}>
                  <mesh name="pCylinder10_pc_modelagem_lambert7_0" geometry={nodes.pCylinder10_pc_modelagem_lambert7_0.geometry} material={materials.pc_modelagem_lambert7} />
                </group>
                <group name="pc_modelagem_pCylinder19" position={[2.48, 4.264, -0.451]} rotation={[0, 0, Math.PI / 2]} scale={[0.848, 0.084, 0.848]}>
                  <group name="transform12_1" />
                </group>
                <group name="pCube18" position={[-0.992, 5.877, 1.511]} scale={[0.187, 3.959, 4.527]}>
                  <mesh name="pCube18_pc_modelagem_lambert13_0" geometry={nodes.pCube18_pc_modelagem_lambert13_0.geometry} material={materials.pc_modelagem_lambert13} />
                </group>
                <group name="pCube19" position={[-0.782, 5.562, -0.305]} scale={[0.239, 0.15, 0.594]}>
                  <mesh name="pCube19_aiStandardSurface6_0" geometry={nodes.pCube19_aiStandardSurface6_0.geometry} material={materials.aiStandardSurface6} />
                </group>
                <group name="pCube20" position={[-0.867, 6.465, -0.389]} scale={[0.215, 0.818, 0.182]}>
                  <mesh name="pCube20_aiStandardSurface6_0" geometry={nodes.pCube20_aiStandardSurface6_0.geometry} material={materials.aiStandardSurface6} />
                </group>
                <group name="pc_modelagem_pCube21" position={[0, 6.685, -2.368]} scale={[1.682, 1.16, 1.125]}>
                  <group name="transform7_1" />
                </group>
                <group name="pCube22" position={[0, 0, -0.205]} scale={[1, 1, 0.91]}>
                  <mesh name="pCube22_aiStandardSurface11_0" geometry={nodes.pCube22_aiStandardSurface11_0.geometry} material={materials.aiStandardSurface11} />
                </group>
                <group name="pc_modelagem_pCylinder21" position={[2.48, 4.264, 1.374]} rotation={[0, 0, Math.PI / 2]} scale={[0.848, 0.084, 0.848]}>
                  <group name="transform10_1" />
                </group>
                <group name="pc_modelagem_pCylinder26" position={[2.48, 4.264, 3.166]} rotation={[0, 0, Math.PI / 2]} scale={[0.848, 0.084, 0.848]}>
                  <group name="transform9_1" />
                </group>
                <group name="pc_modelagem_pCube23" position={[2.198, 4.252, 1.378]} scale={[0.606, 2.517, 5.956]}>
                  <group name="transform11_1" />
                </group>
                <group name="pc_modelagem_back" position={[0, 0, -1000.1]} rotation={[0, -Math.PI / 2, 0]}>
                  <group name="Object_214" />
                </group>
                <group name="pc_modelagem_pCylinder27" position={[-2.608, 0.013, -0.395]} scale={[1.349, 0.933, 0.894]}>
                  <group name="polySurface2" position={[0.069, 0.508, 0.118]} scale={[0.946, 0.934, 0.937]}>
                    <mesh name="polySurface2_aiStandardSurface7_0" geometry={nodes.polySurface2_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} />
                    <mesh name="polySurface2_lambert25_0" geometry={nodes.polySurface2_lambert25_0.geometry} material={materials.lambert25} />
                  </group>
                  <group name="transform38_1" />
                </group>
                <group name="pCube24" position={[0.138, 8.252, -0.218]} scale={[2.393, 0.585, 2.281]}>
                  <mesh name="pCube24_lambert35_0" geometry={nodes.pCube24_lambert35_0.geometry} material={materials.lambert35} />
                </group>
                <group name="pCube25" position={[0.348, 4.104, 4.225]} scale={[2.296, 2.5, 1.152]}>
                  <mesh name="pCube25_pc_modelagem_lambert14_0" geometry={nodes.pCube25_pc_modelagem_lambert14_0.geometry} material={materials.pc_modelagem_lambert14} />
                  <mesh name="pCube25_lambert15_0" geometry={nodes.pCube25_lambert15_0.geometry} material={materials.lambert15} />
                </group>
                <group name="pCube26" position={[0.138, 8.252, 2.364]} scale={[2.393, 0.585, 2.281]}>
                  <mesh name="pCube26_lambert35_0" geometry={nodes.pCube26_lambert35_0.geometry} material={materials.lambert35} />
                </group>
                <group name="pCylinder28" position={[0.168, 8.129, 2.37]} scale={[1.084, 0.331, 1.084]}>
                  <mesh name="pCylinder28_lambert35_0" geometry={nodes.pCylinder28_lambert35_0.geometry} material={materials.lambert35} />
                </group>
                <group name="pCylinder29" position={[1.009, 8.165, 3.285]} scale={[0.096, 0.417, 0.096]}>
                  <mesh name="pCylinder29_pc_modelagem_lambert7_0" geometry={nodes.pCylinder29_pc_modelagem_lambert7_0.geometry} material={materials.pc_modelagem_lambert7} />
                </group>
                <group name="pCylinder30" position={[1.009, 8.165, 1.437]} scale={[0.096, 0.417, 0.096]}>
                  <mesh name="pCylinder30_pc_modelagem_lambert7_0" geometry={nodes.pCylinder30_pc_modelagem_lambert7_0.geometry} material={materials.pc_modelagem_lambert7} />
                </group>
                <group name="pCylinder31" position={[-0.704, 8.165, 1.437]} scale={[0.096, 0.417, 0.096]}>
                  <mesh name="pCylinder31_pc_modelagem_lambert7_0" geometry={nodes.pCylinder31_pc_modelagem_lambert7_0.geometry} material={materials.pc_modelagem_lambert7} />
                </group>
                <group name="pCylinder32" position={[-0.704, 8.165, 3.285]} scale={[0.096, 0.417, 0.096]}>
                  <mesh name="pCylinder32_pc_modelagem_lambert7_0" geometry={nodes.pCylinder32_pc_modelagem_lambert7_0.geometry} material={materials.pc_modelagem_lambert7} />
                </group>
                <group name="pCube27" position={[0.12, 8.171, 1.078]} scale={[2.556, 0.323, 4.935]}>
                  <mesh name="pCube27_lambert35_0" geometry={nodes.pCube27_lambert35_0.geometry} material={materials.lambert35} />
                </group>
                <group name="pCube28" position={[-0.862, 6.22, 1.974]} scale={[0.085, 1.671, 1.695]}>
                  <mesh name="pCube28_aiStandardSurface6_0" geometry={nodes.pCube28_aiStandardSurface6_0.geometry} material={materials.aiStandardSurface6} />
                </group>
                <group name="pCube29" position={[1.233, 8.012, 3.436]} scale={[0.609, 0.149, 0.581]}>
                  <mesh name="pCube29_pc_modelagem_lambert7_0" geometry={nodes.pCube29_pc_modelagem_lambert7_0.geometry} material={materials.pc_modelagem_lambert7} />
                </group>
                <group name="pCube30" position={[-0.865, 8.012, 3.436]} scale={[0.609, 0.149, 0.581]}>
                  <mesh name="pCube30_pc_modelagem_lambert7_0" geometry={nodes.pCube30_pc_modelagem_lambert7_0.geometry} material={materials.pc_modelagem_lambert7} />
                </group>
                <group name="pCube31" position={[-0.865, 8.012, -1.312]} scale={[0.609, 0.149, 0.581]}>
                  <mesh name="pCube31_pc_modelagem_lambert7_0" geometry={nodes.pCube31_pc_modelagem_lambert7_0.geometry} material={materials.pc_modelagem_lambert7} />
                </group>
                <group name="pCube32" position={[1.233, 8.012, -1.312]} scale={[0.609, 0.149, 0.581]}>
                  <mesh name="pCube32_pc_modelagem_lambert7_0" geometry={nodes.pCube32_pc_modelagem_lambert7_0.geometry} material={materials.pc_modelagem_lambert7} />
                </group>
                <group name="pCube36" position={[-0.801, 7.403, 3.717]} scale={[0.217, 0.249, 0.242]}>
                  <group name="transform79" />
                </group>
                <group name="pc_modelagem_pCylinder34" position={[0.168, 6.6, 5.01]} rotation={[Math.PI / 2, 0, 0]} scale={[1.084, 0.865, 1.084]}>
                  <group name="transform13_1" />
                </group>
                <group name="pCube37">
                  <group name="transform76" />
                </group>
                <group name="pc_modelagem_pCylinder35" position={[0.168, 6.6, 4.106]} rotation={[Math.PI / 2, 0, 0]} scale={[1.084, 1.842, 1.084]}>
                  <group name="transform15_1" />
                </group>
                <group name="pCube38" position={[-0.15, 0, 3.969]} scale={[1, 1, 0.176]}>
                  <mesh name="pCube38_lambert37_0" geometry={nodes.pCube38_lambert37_0.geometry} material={materials.lambert37} />
                </group>
                <group name="pCube39" position={[-0.157, -0.002, 4.073]} rotation={[-0.003, 0, 0]} scale={[1, 1, 0.124]}>
                  <mesh name="pCube39_lambert1_0" geometry={nodes.pCube39_lambert1_0.geometry} material={materials.lambert1} />
                </group>
                <group name="pCube40" position={[-0.832, 6.032, 3.742]} scale={[0.152, 0.174, 0.169]}>
                  <group name="transform81" />
                </group>
                <group name="pCube41" position={[-0.832, 5.796, 3.742]} scale={[0.152, 0.174, 0.169]}>
                  <group name="transform80" />
                </group>
                <group name="pCube42" position={[-0.868, 6.734, 3.741]} scale={[0.163, 0.187, 0.182]}>
                  <group name="transform84" />
                </group>
                <group name="pCube43" position={[-0.868, 6.949, 3.74]} scale={[0.163, 0.187, 0.182]}>
                  <group name="transform86" />
                </group>
                <group name="pCube44" position={[-0.868, 7.172, 3.737]} scale={[0.163, 0.187, 0.182]}>
                  <group name="transform85" />
                </group>
                <group name="pCube45" position={[-0.832, 6.511, 3.742]} scale={[0.152, 0.174, 0.169]}>
                  <group name="transform83" />
                </group>
                <group name="pCube46" position={[-0.832, 6.275, 3.742]} scale={[0.152, 0.174, 0.169]}>
                  <group name="transform82" />
                </group>
                <group name="pc_modelagem_pCylinder36" position={[0.458, 6.172, -0.112]} rotation={[0, 0, Math.PI / 2]} scale={[0.064, 1.268, 0.121]}>
                  <group name="transform74_1" />
                </group>
                <group name="pc_modelagem_pCylinder37" position={[0.168, 6.6, 4.902]} rotation={[Math.PI / 2, 0, 0]} scale={[0.284, 0.056, 0.284]}>
                  <group name="transform30_1" />
                </group>
                <group name="pc_modelagem_pCube47" position={[0.901, 6.603, 4.891]} scale={[1, 1, 0.089]}>
                  <group name="transform31_1" />
                </group>
                <group name="pCube48" position={[-0.332, 4.246, 0.661]} scale={[1.278, 0.187, 2.284]}>
                  <mesh name="pCube48_lambert1_0" geometry={nodes.pCube48_lambert1_0.geometry} material={materials.lambert1} />
                </group>
                <group name="pCube49" position={[-0.332, 4.567, 0.661]} scale={[1.278, 0.187, 2.284]}>
                  <mesh name="pCube49_aiStandardSurface6_0" geometry={nodes.pCube49_aiStandardSurface6_0.geometry} material={materials.aiStandardSurface6} />
                </group>
                <group name="pc_modelagem_pCylinder38" position={[0.458, 6.3, -0.112]} rotation={[0, 0, Math.PI / 2]} scale={[0.064, 1.268, 0.121]}>
                  <group name="transform72_1" />
                </group>
                <group name="pc_modelagem_pCylinder39" position={[0.458, 6.421, -0.112]} rotation={[0, 0, Math.PI / 2]} scale={[0.064, 1.268, 0.121]}>
                  <group name="transform73_1" />
                </group>
                <group name="pc_modelagem_pCylinder40" position={[0.458, 6.545, -0.112]} rotation={[0, 0, Math.PI / 2]} scale={[0.064, 1.268, 0.121]}>
                  <group name="transform71_1" />
                </group>
                <group name="pc_modelagem_pCylinder41" position={[0.458, 6.671, -0.112]} rotation={[0, 0, Math.PI / 2]} scale={[0.064, 1.268, 0.121]}>
                  <group name="transform70_1" />
                </group>
                <group name="pc_modelagem_pCylinder42" position={[0.458, 6.792, -0.112]} rotation={[0, 0, Math.PI / 2]} scale={[0.064, 1.268, 0.121]}>
                  <group name="transform69_1" />
                </group>
                <group name="pc_modelagem_pCylinder43" position={[0.458, 7.04, -0.112]} rotation={[0, 0, Math.PI / 2]} scale={[0.064, 1.268, 0.121]}>
                  <group name="transform67_1" />
                </group>
                <group name="pc_modelagem_pCylinder44" position={[0.458, 6.914, -0.112]} rotation={[0, 0, Math.PI / 2]} scale={[0.064, 1.268, 0.121]}>
                  <group name="transform68_1" />
                </group>
                <group name="pc_modelagem_pCylinder45" position={[0.458, 12.149, -0.112]} rotation={[0, 0, Math.PI / 2]} scale={[0.064, 1.268, 0.121]}>
                  <group name="transform24_1" />
                </group>
                <group name="pc_modelagem_pCylinder46" position={[0.458, 12.024, -0.112]} rotation={[0, 0, Math.PI / 2]} scale={[0.064, 1.268, 0.121]}>
                  <group name="transform23_1" />
                </group>
                <group name="pc_modelagem_pCylinder47" position={[0.458, 11.901, -0.112]} rotation={[0, 0, Math.PI / 2]} scale={[0.064, 1.268, 0.121]}>
                  <group name="transform22_1" />
                </group>
                <group name="pc_modelagem_pCylinder48" position={[0.458, 11.78, -0.112]} rotation={[0, 0, Math.PI / 2]} scale={[0.064, 1.268, 0.121]}>
                  <group name="transform21_1" />
                </group>
                <group name="pc_modelagem_pCylinder49" position={[0.458, 11.654, -0.112]} rotation={[0, 0, Math.PI / 2]} scale={[0.064, 1.268, 0.121]}>
                  <group name="transform20_1" />
                </group>
                <group name="pc_modelagem_pCylinder50" position={[0.458, 11.53, -0.112]} rotation={[0, 0, Math.PI / 2]} scale={[0.064, 1.268, 0.121]}>
                  <group name="transform19_1" />
                </group>
                <group name="pc_modelagem_pCylinder51" position={[0.458, 11.409, -0.112]} rotation={[0, 0, Math.PI / 2]} scale={[0.064, 1.268, 0.121]}>
                  <group name="transform18_1" />
                </group>
                <group name="pc_modelagem_pCylinder52" position={[0.458, 11.281, -0.112]} rotation={[0, 0, Math.PI / 2]} scale={[0.064, 1.268, 0.121]}>
                  <group name="transform17_1" />
                </group>
                <group name="pCylinder53" position={[-0.321, 5.647, 6.425]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.469, 0.575, 0.562]}>
                  <mesh name="pCylinder53_aiStandardSurface9_0" geometry={nodes.pCylinder53_aiStandardSurface9_0.geometry} material={materials.aiStandardSurface9} />
                </group>
                <group name="pCube50" position={[-0.853, 7.043, 3.533]} scale={[0.217, 0.312, 0.257]}>
                  <mesh name="pCube50_aiStandardSurface6_0" geometry={nodes.pCube50_aiStandardSurface6_0.geometry} material={materials.aiStandardSurface6} />
                </group>
                <group name="pCube51" position={[-0.853, 7.435, 3.53]} scale={[0.217, 0.312, 0.257]}>
                  <mesh name="pCube51_aiStandardSurface6_0" geometry={nodes.pCube51_aiStandardSurface6_0.geometry} material={materials.aiStandardSurface6} />
                </group>
                <group name="pc_modelagem_pCylinder54" position={[1.686, 6.172, 1.519]} rotation={[0, 0, Math.PI / 2]} scale={[0.121, 2.112, 0.202]}>
                  <group name="transform26_1" />
                </group>
                <group name="pc_modelagem_pCylinder55" position={[1.686, 6.438, 1.519]} rotation={[0, 0, Math.PI / 2]} scale={[0.121, 2.112, 0.202]}>
                  <group name="transform25_1" />
                </group>
                <group name="pc_modelagem_pCube52" position={[-0.639, 6.603, 4.891]} rotation={[0, 0, Math.PI]} scale={[1, 1, 0.089]}>
                  <group name="transform29_1" />
                </group>
                <group name="pc_modelagem_pCube53" position={[-0.639, 6.603, 14.618]} rotation={[0, 0, Math.PI]} scale={[1, 1, 0.089]}>
                  <group name="transform28_1" />
                </group>
                <group name="pc_modelagem_pCube54" position={[0.901, 6.603, 14.618]} scale={[1, 1, 0.089]}>
                  <group name="transform27_1" />
                </group>
                <group name="pc_modelagem_pCube55" position={[-4.037, 1.48, -9.727]} rotation={[0, 0, -0.663]}>
                  <group name="transform33_1" />
                </group>
                <group name="pc_modelagem_pCube56" position={[-6.252, 4.911, -9.727]} rotation={[0, 0, -1.292]}>
                  <group name="transform35_1" />
                </group>
                <group name="pc_modelagem_pCube57" position={[-5.991, 9.079, -9.727]} rotation={[0, 0, -1.935]}>
                  <group name="transform34_1" />
                </group>
                <group name="pc_modelagem_pCube58" position={[-3.157, 12.33, -9.727]} rotation={[0, 0, -2.6]}>
                  <group name="transform32_1" />
                </group>
                <group name="pCube60" position={[-0.801, 6.653, 4.699]} rotation={[0, 0, -0.764]} scale={[0.217, 0.249, 0.065]}>
                  <mesh name="pCube60_pc_modelagem_lambert7_0" geometry={nodes.pCube60_pc_modelagem_lambert7_0.geometry} material={materials.pc_modelagem_lambert7} />
                </group>
                <group name="pCube62" position={[1.899, 5.057, -0.003]} rotation={[0.002, 0, 0]} scale={[0, 7.815, 9.511]}>
                  <mesh name="pCube62_blinn24_0" geometry={nodes.pCube62_blinn24_0.geometry} material={materials.blinn24} />
                </group>
                <group name="pCylinder57" position={[0.039, 7.417, -5.323]} rotation={[Math.PI / 2, 0, 0]} scale={[0.379, 0.038, 0.359]}>
                  <mesh name="pCylinder57_pc_modelagem_blinn18_0" geometry={nodes.pCylinder57_pc_modelagem_blinn18_0.geometry} material={materials.pc_modelagem_blinn18} />
                </group>
                <group name="pCube64" position={[-0.235, 0.818, -5.868]} scale={[1, 1, 0.143]}>
                  <mesh name="pCube64_pc_modelagem_blinn16_0" geometry={nodes.pCube64_pc_modelagem_blinn16_0.geometry} material={materials.pc_modelagem_blinn16} />
                </group>
                <group name="pCube65" position={[-0.229, 0.524, -6.098]} scale={[1.038, 1.038, 0.22]}>
                  <mesh name="pCube65_lambert1_0" geometry={nodes.pCube65_lambert1_0.geometry} material={materials.lambert1} />
                </group>
                <group name="pCylinder58" position={[0.039, 5, -5.323]} rotation={[Math.PI / 2, 0, 0]} scale={[0.379, 0.038, 0.359]}>
                  <mesh name="pCylinder58_pc_modelagem_blinn18_0" geometry={nodes.pCylinder58_pc_modelagem_blinn18_0.geometry} material={materials.pc_modelagem_blinn18} />
                </group>
                <group name="pCube67" position={[-0.235, -1.6, -5.868]} scale={[1, 1, 0.143]}>
                  <mesh name="pCube67_pc_modelagem_blinn16_0" geometry={nodes.pCube67_pc_modelagem_blinn16_0.geometry} material={materials.pc_modelagem_blinn16} />
                </group>
                <group name="pCube68" position={[-0.229, -1.864, -6.098]} scale={[1.038, 1.038, 0.22]}>
                  <mesh name="pCube68_lambert1_0" geometry={nodes.pCube68_lambert1_0.geometry} material={materials.lambert1} />
                </group>
                <group name="pCylinder59" position={[0.03, 2.633, -5.323]} rotation={[Math.PI / 2, 0, 0]} scale={[0.379, 0.038, 0.359]}>
                  <mesh name="pCylinder59_pc_modelagem_blinn18_0" geometry={nodes.pCylinder59_pc_modelagem_blinn18_0.geometry} material={materials.pc_modelagem_blinn18} />
                </group>
                <group name="pCube70" position={[-0.235, -3.966, -5.868]} scale={[1, 1, 0.143]}>
                  <mesh name="pCube70_pc_modelagem_blinn16_0" geometry={nodes.pCube70_pc_modelagem_blinn16_0.geometry} material={materials.pc_modelagem_blinn16} />
                </group>
                <group name="pCube71" position={[-0.229, -4.227, -6.098]} scale={[1.038, 1.038, 0.22]}>
                  <mesh name="pCube71_lambert1_0" geometry={nodes.pCube71_lambert1_0.geometry} material={materials.lambert1} />
                </group>
                <group name="pc_modelagem_pCube72" position={[4.685, -1.37, -2.827]} scale={[1.331, 1.331, 0.719]}>
                  <group name="transform37_1" />
                </group>
                <group name="pc_modelagem_pCylinder60" position={[4.896, 7.417, 0.653]} rotation={[Math.PI / 2, 0, 0]} scale={[0.161, 0.079, 0.153]}>
                  <group name="transform36_1" />
                </group>
                <group name="pc_modelagem_pCube75" position={[-5.218, 13.661, -1.15]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.725}>
                  <group name="polySurface15_1">
                    <group name="transform46_1" />
                  </group>
                  <group name="polySurface16_1">
                    <group name="transform53_1" />
                  </group>
                  <group name="polySurface17_1">
                    <group name="transform52_1" />
                  </group>
                  <group name="polySurface18_1">
                    <group name="transform43_1" />
                  </group>
                  <group name="polySurface19_1">
                    <group name="transform51_1" />
                  </group>
                  <group name="polySurface20_1">
                    <group name="transform50_1" />
                  </group>
                  <group name="polySurface21_1">
                    <group name="transform49_1" />
                  </group>
                  <group name="polySurface22_1">
                    <group name="transform44_1" />
                  </group>
                  <group name="polySurface23_1">
                    <group name="transform47_1" />
                  </group>
                  <group name="polySurface24_2">
                    <group name="transform54_1" />
                  </group>
                  <group name="polySurface25_1">
                    <group name="transform45_1" />
                  </group>
                  <group name="polySurface26_1" position={[-0.021, 0, 0]}>
                    <group name="transform48_1" />
                  </group>
                  <group name="transform42_1" />
                </group>
                <group name="pc_modelagem_pCylinder61" position={[2.89, 3.994, 0.833]} rotation={[0, 0, Math.PI / 2]} scale={[0.808, 0.166, 0.808]}>
                  <group name="transform40_1" />
                </group>
                <group name="pc_modelagem_pCylinder62" position={[2.89, 3.994, 0.833]} rotation={[0, 0, Math.PI / 2]} scale={[0.743, 0.607, 0.743]}>
                  <group name="transform39_1" />
                </group>
                <group name="pCylinder63" position={[-1.406, 0.164, 0.014]} scale={[0.739, 1, 1]}>
                  <mesh name="pCylinder63_pc_modelagem_blinn12_0" geometry={nodes.pCylinder63_pc_modelagem_blinn12_0.geometry} material={materials.pc_modelagem_blinn12} />
                </group>
                <group name="pCylinder64" position={[4.164, 4.807, 1.536]} rotation={[0, 0, Math.PI / 2]}>
                  <mesh name="pCylinder64_pc_modelagem_lambert7_0" geometry={nodes.pCylinder64_pc_modelagem_lambert7_0.geometry} material={materials.pc_modelagem_lambert7} />
                </group>
                <group name="pCylinder65" position={[-1.406, 0.164, -1.623]} scale={[0.739, 1, 1]}>
                  <mesh name="pCylinder65_pc_modelagem_blinn12_0" geometry={nodes.pCylinder65_pc_modelagem_blinn12_0.geometry} material={materials.pc_modelagem_blinn12} />
                </group>
                <group name="pc_modelagem_pCube76" position={[-5.218, 13.661, -3.731]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.725}>
                  <group name="polySurface3_1">
                    <group name="transform59_1" />
                  </group>
                  <group name="polySurface4_1">
                    <group name="transform61_1" />
                  </group>
                  <group name="polySurface5_1">
                    <group name="transform60_1" />
                  </group>
                  <group name="polySurface6_1">
                    <group name="transform58_1" />
                  </group>
                  <group name="polySurface7_2">
                    <group name="transform66_1" />
                  </group>
                  <group name="polySurface8_1">
                    <group name="transform65_1" />
                  </group>
                  <group name="polySurface9_1">
                    <group name="transform62_1" />
                  </group>
                  <group name="polySurface10_1">
                    <group name="transform64_1" />
                  </group>
                  <group name="polySurface11_1">
                    <group name="transform57_1" />
                  </group>
                  <group name="polySurface12_1">
                    <group name="transform56_1" />
                  </group>
                  <group name="polySurface13_1">
                    <group name="transform63_1" />
                  </group>
                  <group name="polySurface14_1" position={[-0.021, 0, 0]}>
                    <group name="transform55_1" />
                  </group>
                  <group name="transform41_1" />
                </group>
                <group name="pCylinder66" position={[4.164, 4.807, -1.045]} rotation={[0, 0, Math.PI / 2]}>
                  <mesh name="pCylinder66_pc_modelagem_lambert7_0" geometry={nodes.pCylinder66_pc_modelagem_lambert7_0.geometry} material={materials.pc_modelagem_lambert7} />
                </group>
                <group name="pCylinder67" position={[-1.406, 0.164, 1.645]} scale={[0.739, 1, 1]}>
                  <mesh name="pCylinder67_pc_modelagem_blinn12_0" geometry={nodes.pCylinder67_pc_modelagem_blinn12_0.geometry} material={materials.pc_modelagem_blinn12} />
                </group>
                <group name="pCylinder68" position={[0.004, 6.595, 4.796]} rotation={[Math.PI / 2, 0, 0]} scale={[0.342, 0.153, 0.342]}>
                  <mesh name="pCylinder68_pc_modelagem_blinn18_0" geometry={nodes.pCylinder68_pc_modelagem_blinn18_0.geometry} material={materials.pc_modelagem_blinn18} />
                </group>
                <group name="pCylinder69" position={[0.865, 4.167, 2.474]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.229, 0.054, 0.229]}>
                  <mesh name="pCylinder69_pc_modelagem_blinn18_0" geometry={nodes.pCylinder69_pc_modelagem_blinn18_0.geometry} material={materials.pc_modelagem_blinn18} />
                </group>
                <group name="pCylinder70" position={[0.865, 4.167, 0.849]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.229, 0.054, 0.229]}>
                  <mesh name="pCylinder70_pc_modelagem_blinn18_0" geometry={nodes.pCylinder70_pc_modelagem_blinn18_0.geometry} material={materials.pc_modelagem_blinn18} />
                </group>
                <group name="pCylinder71" position={[0.865, 4.167, -0.815]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.229, 0.054, 0.229]}>
                  <mesh name="pCylinder71_pc_modelagem_blinn18_0" geometry={nodes.pCylinder71_pc_modelagem_blinn18_0.geometry} material={materials.pc_modelagem_blinn18} />
                </group>
                <group name="pCube78" position={[0.009, 6.674, 5.047]} scale={[2.668, 2.487, 0.055]}>
                  <mesh name="pCube78_pc_modelagem_blinn1_0" geometry={nodes.pCube78_pc_modelagem_blinn1_0.geometry} material={materials.pc_modelagem_blinn1} />
                </group>
                <group name="pCube79" position={[0.12, 8.095, 1.078]} scale={[2.611, 0.284, 5.04]}>
                  <mesh name="pCube79_lambert35_0" geometry={nodes.pCube79_lambert35_0.geometry} material={materials.lambert35} />
                </group>
                <group name="pCube80" position={[-0.853, 6.671, 3.532]} scale={[0.217, 0.312, 0.257]}>
                  <mesh name="pCube80_aiStandardSurface6_0" geometry={nodes.pCube80_aiStandardSurface6_0.geometry} material={materials.aiStandardSurface6} />
                </group>
                <group name="pCylinder72" position={[0, 1.309, -0.298]} scale={[1, 0.779, 0.777]}>
                  <mesh name="pCylinder72_aiStandardSurface5_0" geometry={nodes.pCylinder72_aiStandardSurface5_0.geometry} material={materials.aiStandardSurface5} />
                </group>
                <group name="pCube82" position={[-0.867, 6.403, 0.842]} scale={[0.215, 2.272, 0.135]}>
                  <mesh name="pCube82_aiStandardSurface6_0" geometry={nodes.pCube82_aiStandardSurface6_0.geometry} material={materials.aiStandardSurface6} />
                </group>
                <group name="pCube83" position={[-0.457, 6.411, 0.844]} scale={[0.681, 2.094, 0.105]}>
                  <mesh name="pCube83_lambert21_0" geometry={nodes.pCube83_lambert21_0.geometry} material={materials.lambert21} />
                  <mesh name="pCube83_lambert27_0" geometry={nodes.pCube83_lambert27_0.geometry} material={materials.lambert27} />
                </group>
                <group name="pCube86" position={[0.01, 5.047, -4.961]} scale={[3.411, 7.813, 0.086]}>
                  <mesh name="pCube86_pc_modelagem_blinn17_0" geometry={nodes.pCube86_pc_modelagem_blinn17_0.geometry} material={materials.pc_modelagem_blinn17} />
                </group>
                <group name="pCube89" position={[0, 4.153, 4.228]} scale={[2.805, 2.375, 1.111]}>
                  <mesh name="pCube89_lambert1_0" geometry={nodes.pCube89_lambert1_0.geometry} material={materials.lambert1} />
                </group>
                <group name="pCube90" position={[-0.867, 6.403, 0.598]} scale={[0.215, 2.272, 0.135]}>
                  <mesh name="pCube90_aiStandardSurface6_0" geometry={nodes.pCube90_aiStandardSurface6_0.geometry} material={materials.aiStandardSurface6} />
                </group>
                <group name="pCube92" position={[-0.867, 6.403, 0.346]} scale={[0.215, 2.272, 0.135]}>
                  <mesh name="pCube92_aiStandardSurface6_0" geometry={nodes.pCube92_aiStandardSurface6_0.geometry} material={materials.aiStandardSurface6} />
                </group>
                <group name="pCube94" position={[-0.867, 6.403, 0.093]} scale={[0.215, 2.272, 0.135]}>
                  <mesh name="pCube94_aiStandardSurface6_0" geometry={nodes.pCube94_aiStandardSurface6_0.geometry} material={materials.aiStandardSurface6} />
                </group>
                <group name="pCube96" position={[-0.079, 9.161, -5.229]} rotation={[1.152, 0, 0]} scale={[0.342, 0.342, 0.293]}>
                  <mesh name="pCube96_lambert1_0" geometry={nodes.pCube96_lambert1_0.geometry} material={materials.lambert1} />
                </group>
                <group name="pCube97" position={[0.986, 9.197, -5.243]} rotation={[1.152, 0, 0]} scale={[0.197, 0.197, 0.169]}>
                  <mesh name="pCube97_lambert1_0" geometry={nodes.pCube97_lambert1_0.geometry} material={materials.lambert1} />
                </group>
                <group name="pCube98" position={[1.298, 9.197, -5.243]} rotation={[1.152, 0, 0]} scale={[0.197, 0.197, 0.169]}>
                  <mesh name="pCube98_lambert1_0" geometry={nodes.pCube98_lambert1_0.geometry} material={materials.lambert1} />
                </group>
                <group name="pCube99" position={[-1.437, 9.182, -5.243]} rotation={[1.152, 0, -Math.PI]} scale={[-0.342, -0.146, -0.317]}>
                  <group name="transform75" />
                </group>
                <group name="pCube100" position={[-1.009, 9.182, -5.243]} rotation={[1.152, 0, -Math.PI]} scale={[-0.342, -0.146, -0.317]}>
                  <group name="transform77" />
                </group>
                <group name="pCube101">
                  <group name="transform78" />
                </group>
                <group name="pCube103" position={[0.08, -0.537, -2.308]} scale={[1.09, 1.09, 1.713]}>
                  <mesh name="pCube103_aiStandardSurface6_0" geometry={nodes.pCube103_aiStandardSurface6_0.geometry} material={materials.aiStandardSurface6} />
                </group>
                <group name="directionalLight1" position={[24.089, 7.109, 0]} rotation={[Math.PI / 2, 0, -1.61]}>
                  <group name="Object_495" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_496" />
                  </group>
                </group>
                <group name="directionalLight2" position={[0, 6.551, 1.539]} rotation={[Math.PI / 2, 0, 1.066]} scale={[1, 1, 0.677]}>
                  <group name="Object_498" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_499" />
                  </group>
                </group>
                <group name="directionalLight3" position={[-0.067, 6.551, 2.423]} rotation={[Math.PI / 2, 0, 2.184]} scale={[1, 1, 0.677]}>
                  <group name="Object_501" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_502" />
                  </group>
                </group>
                <group name="directionalLight4" position={[-0.067, 7.702, 2.423]} rotation={[-2.988, -0.952, -3.016]} scale={[1, 1, 0.366]}>
                  <group name="Object_504" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_505" />
                  </group>
                </group>
                <group name="directionalLight5" position={[-0.067, 7.702, -0.274]} rotation={[-2.988, -0.952, -3.016]} scale={[1, 1, 0.366]}>
                  <group name="Object_507" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_508" />
                  </group>
                </group>
                <group name="directionalLight6" position={[0.025, 6.63, 4.373]} rotation={[-1.371, -1.459, -2.942]} scale={[1, 1, 0.679]}>
                  <group name="Object_510" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_511" />
                  </group>
                </group>
                <group name="directionalLight7" position={[0.025, 6.63, 4.373]} rotation={[-1.371, -1.459, -2.942]} scale={[1, 1, 0.141]}>
                  <group name="Object_513" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_514" />
                  </group>
                </group>
                <group name="directionalLight8" position={[0.025, 6.63, 4.685]} rotation={[-1.371, -1.459, 0.231]} scale={[1.736, 1.736, 1.178]}>
                  <group name="Object_516" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_517" />
                  </group>
                </group>
                <group name="directionalLight9" position={[-0.733, 5.547, 0.281]} rotation={[-0.024, 0.079, 1.462]} scale={[0.829, 0.829, 0.587]}>
                  <group name="Object_519" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_520" />
                  </group>
                </group>
                <group name="directionalLight10" position={[0.735, 4.242, 0.98]} rotation={[0.008, 0.004, 1.462]} scale={[1.655, 1.655, 1.261]}>
                  <group name="Object_522" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_523" />
                  </group>
                </group>
                <group name="directionalLight11" position={[0.735, 4.242, 2.583]} rotation={[0.008, 0.004, 1.462]} scale={[1.655, 1.655, 1.261]}>
                  <group name="Object_525" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_526" />
                  </group>
                </group>
                <group name="directionalLight12" position={[0.735, 4.242, -0.787]} rotation={[0.008, 0.004, 1.462]} scale={[1.655, 1.655, 1.261]}>
                  <group name="Object_528" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_529" />
                  </group>
                </group>
                <group name="directionalLight13" position={[-0.004, 5.018, -5.489]} rotation={[1.288, 1.457, 0.288]} scale={[1.655, 1.655, 1.161]}>
                  <group name="Object_531" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_532" />
                  </group>
                </group>
                <group name="directionalLight14" position={[-0.004, 2.753, -5.489]} rotation={[1.288, 1.457, 0.288]} scale={[1.655, 1.655, 1.161]}>
                  <group name="Object_534" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_535" />
                  </group>
                </group>
                <group name="directionalLight15" position={[-0.004, 7.363, -5.489]} rotation={[1.288, 1.457, 0.288]} scale={[1.655, 1.655, 1.161]}>
                  <group name="Object_537" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_538" />
                  </group>
                </group>
                <group name="pCube104" position={[-0.457, 6.411, 0.597]} scale={[0.681, 2.094, 0.105]}>
                  <mesh name="pCube104_lambert21_0" geometry={nodes.pCube104_lambert21_0.geometry} material={materials.lambert21} />
                  <mesh name="pCube104_lambert27_0" geometry={nodes.pCube104_lambert27_0.geometry} material={materials.lambert27} />
                </group>
                <group name="pCube105" position={[-0.457, 6.411, 0.093]} scale={[0.681, 2.094, 0.105]}>
                  <mesh name="pCube105_lambert21_0" geometry={nodes.pCube105_lambert21_0.geometry} material={materials.lambert21} />
                  <mesh name="pCube105_lambert27_0" geometry={nodes.pCube105_lambert27_0.geometry} material={materials.lambert27} />
                </group>
                <group name="pCube106" position={[-0.457, 6.411, 0.339]} scale={[0.681, 2.094, 0.105]}>
                  <mesh name="pCube106_lambert21_0" geometry={nodes.pCube106_lambert21_0.geometry} material={materials.lambert21} />
                  <mesh name="pCube106_lambert27_0" geometry={nodes.pCube106_lambert27_0.geometry} material={materials.lambert27} />
                </group>
                <group name="directionalLight16" position={[-0.733, 6.799, 0.281]} rotation={[-0.024, 0.079, 1.462]} scale={[0.829, 0.829, 0.587]}>
                  <group name="Object_549" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_550" />
                  </group>
                </group>
                <group name="directionalLight17" position={[14.218, 6.047, 5.986]} rotation={[Math.PI / 2, 0, -1.165]}>
                  <group name="Object_552" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_553" />
                  </group>
                </group>
                <group name="pCube107" position={[0, 0.012, -0.016]}>
                  <mesh name="pCube107_aiStandardSurface2_0" geometry={nodes.pCube107_aiStandardSurface2_0.geometry} material={materials.aiStandardSurface2} />
                </group>
                <group name="pCylinder73" position={[-1.474, 0.601, -4.548]} scale={0.168}>
                  <mesh name="pCylinder73_lambert33_0" geometry={nodes.pCylinder73_lambert33_0.geometry} material={materials.lambert33} />
                </group>
                <group name="pCylinder74" position={[1.27, 0.601, -4.548]} scale={0.168}>
                  <mesh name="pCylinder74_lambert33_0" geometry={nodes.pCylinder74_lambert33_0.geometry} material={materials.lambert33} />
                </group>
                <group name="pCylinder75" position={[-1.474, 0.601, 4.405]} scale={0.168}>
                  <mesh name="pCylinder75_lambert33_0" geometry={nodes.pCylinder75_lambert33_0.geometry} material={materials.lambert33} />
                </group>
                <group name="pCylinder76" position={[1.27, 0.601, 4.405]} scale={0.168}>
                  <mesh name="pCylinder76_lambert33_0" geometry={nodes.pCylinder76_lambert33_0.geometry} material={materials.lambert33} />
                </group>
                <group name="pCube110" position={[2.035, 5.775, -5.849]}>
                  <mesh name="pCube110_lambert31_0" geometry={nodes.pCube110_lambert31_0.geometry} material={materials.lambert31} />
                </group>
                <group name="pCube112" position={[-1.035, 5.158, -1.298]} scale={[0.098, 1.124, 0.783]}>
                  <mesh name="pCube112_lambert29_0" geometry={nodes.pCube112_lambert29_0.geometry} material={materials.lambert29} />
                  <mesh name="pCube112_lambert28_0" geometry={nodes.pCube112_lambert28_0.geometry} material={materials.lambert28} />
                </group>
                <group name="pCube116" position={[-1.046, 5.729, -1.095]} scale={[0.023, 0.054, 0.094]}>
                  <mesh name="pCube116_blinn25_0" geometry={nodes.pCube116_blinn25_0.geometry} material={materials.blinn25} />
                  <mesh name="pCube116_lambert30_0" geometry={nodes.pCube116_lambert30_0.geometry} material={materials.lambert30} />
                </group>
                <group name="pCube118" position={[-1.046, 7.276, -1.095]} scale={[0.023, 0.054, 0.094]}>
                  <mesh name="pCube118_blinn25_0" geometry={nodes.pCube118_blinn25_0.geometry} material={materials.blinn25} />
                  <mesh name="pCube118_lambert30_0" geometry={nodes.pCube118_lambert30_0.geometry} material={materials.lambert30} />
                </group>
                <group name="pCube119" position={[-1.035, 6.707, -1.298]} scale={[0.098, 1.124, 0.783]}>
                  <mesh name="pCube119_lambert29_0" geometry={nodes.pCube119_lambert29_0.geometry} material={materials.lambert29} />
                  <mesh name="pCube119_lambert28_0" geometry={nodes.pCube119_lambert28_0.geometry} material={materials.lambert28} />
                </group>
                <group name="pCube120" position={[-2.16, 5.775, -5.849]} rotation={[-Math.PI, 0, 0]} scale={[-0.871, -1, -1]}>
                  <mesh name="pCube120_lambert31_0" geometry={nodes.pCube120_lambert31_0.geometry} material={materials.lambert31} />
                </group>
                <group name="pCylinder77" position={[1.714, 8.499, -4.347]} rotation={[0, 0, Math.PI / 2]} scale={[0.092, 0.204, 0.092]}>
                  <mesh name="pCylinder77_lambert32_0" geometry={nodes.pCylinder77_lambert32_0.geometry} material={materials.lambert32} />
                </group>
                <group name="pCylinder78" position={[1.714, 1.702, -4.347]} rotation={[0, 0, Math.PI / 2]} scale={[0.092, 0.204, 0.092]}>
                  <mesh name="pCylinder78_lambert32_0" geometry={nodes.pCylinder78_lambert32_0.geometry} material={materials.lambert32} />
                </group>
                <group name="pCylinder79" position={[1.714, 1.702, 4.236]} rotation={[0, 0, Math.PI / 2]} scale={[0.092, 0.204, 0.092]}>
                  <mesh name="pCylinder79_lambert32_0" geometry={nodes.pCylinder79_lambert32_0.geometry} material={materials.lambert32} />
                </group>
                <group name="pCylinder80" position={[1.714, 8.499, 4.236]} rotation={[0, 0, Math.PI / 2]} scale={[0.092, 0.204, 0.092]}>
                  <mesh name="pCylinder80_lambert32_0" geometry={nodes.pCylinder80_lambert32_0.geometry} material={materials.lambert32} />
                </group>
                <group name="pCylinder81" position={[5.222, 0, 0]}>
                  <group name="transform88" />
                </group>
                <group name="pCylinder82" position={[5.222, 0.087, 0]} scale={[0.829, 1.021, 0.829]}>
                  <group name="transform87" />
                </group>
                <group name="pCylinder83" position={[0.103, 3.113, 0]} scale={0.219}>
                  <mesh name="pCylinder83_lambert43_0" geometry={nodes.pCylinder83_lambert43_0.geometry} material={materials.lambert43} />
                </group>
                <group name="pCube121" position={[1.18, 3.604, 1.52]} scale={0.392}>
                  <mesh name="pCube121_blinn26_0" geometry={nodes.pCube121_blinn26_0.geometry} material={materials.blinn26} />
                </group>
                <group name="pCylinder84" position={[0.103, 3.113, 2.508]} scale={0.219}>
                  <mesh name="pCylinder84_lambert43_0" geometry={nodes.pCylinder84_lambert43_0.geometry} material={materials.lambert43} />
                </group>
                <group name="pCube122" position={[1.18, 3.392, -1.764]} scale={0.392}>
                  <mesh name="pCube122_blinn26_0" geometry={nodes.pCube122_blinn26_0.geometry} material={materials.blinn26} />
                </group>
                <group name="pCylinder85" position={[-1.032, 6.246, 1.599]} rotation={[0, 0, Math.PI / 2]} scale={0.177}>
                  <mesh name="pCylinder85_lambert1_0" geometry={nodes.pCylinder85_lambert1_0.geometry} material={materials.lambert1} />
                </group>
                <group name="pCylinder86" position={[-1.032, 6.589, 1.599]} rotation={[0, 0, Math.PI / 2]} scale={0.177}>
                  <mesh name="pCylinder86_lambert1_0" geometry={nodes.pCylinder86_lambert1_0.geometry} material={materials.lambert1} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/machine.glb')
