/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/vision.glb 
Author: Navarion (https://sketchfab.com/Navarion)
License: COPYRIGHT TO Navarion
Source: https://sketchfab.com/3d-models/apple-vision-pro-ios16-8bd7123015ee4509b1c312f54a877597
Title: apple_vision_pro_ios16
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function VisionModel(props) {
  const { nodes, materials } = useGLTF('/models/vision.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.05}>
        <mesh geometry={nodes.NCTuWVhPfXbauhX.geometry} material={materials.cfENkBJbuidhJQR} />
        <mesh geometry={nodes.MNXHJkKVjmbUNKU.geometry} material={materials.oTqiLbrwcjsRgMt} />
        <mesh geometry={nodes.dbHbxcqmrAncXcC.geometry} material={materials.VphdCyWbkVqOTZM} />
        <mesh geometry={nodes.RMjnjXyMgoTxvNO.geometry} material={materials.vooHjZuayuJGiMQ} />
        <mesh geometry={nodes.PmnjxmiXJTgjNWb.geometry} material={materials.qDOcIjVpElQVnfu} />
        <mesh geometry={nodes.maRjJfyAOWUFfqI.geometry} material={materials.ZOxfklNhssATaVX} />
        <mesh geometry={nodes.yHomCHSOPycwYvw.geometry} material={materials.MQCEVrylLIUQrVK} />
        <mesh geometry={nodes.ZpISlXViQsOjnoI.geometry} material={materials.AAfeebOMlIFREnV} />
        <mesh geometry={nodes.nSxxllOTLoQHyQZ.geometry} material={materials.AAfeebOMlIFREnV} />
        <mesh geometry={nodes.RfUlkBWLMcnnjDZ.geometry} material={materials.euiQmuWDHAWaTrM} />
        <mesh geometry={nodes.QJrVTzJCWMTTMlr.geometry} material={materials.WSSwRvibmqaLYZi} />
        <mesh geometry={nodes.iSAWOSRcnEglMgD.geometry} material={materials.qJCgguKxFcHIxWa} />
        <mesh geometry={nodes.cZcyOzYlhNSplIL.geometry} material={materials.YfKnpdtpUYsluRm} />
        <mesh geometry={nodes.EbmJgvvXipWjEMi.geometry} material={materials.BCKXYWKgOWAMzzp} />
        <mesh geometry={nodes.xoJVrtkFfggFByx.geometry} material={materials.XKlUGvPEIYYLEPM} />
        <mesh geometry={nodes.NMVTgvZNMHRVFee.geometry} material={materials.ucekphvVRyoLWgE} />
        <mesh geometry={nodes.UDHdONgBtzYRwyk.geometry} material={materials.jOkVLpNIDGFLUJe} />
        <mesh geometry={nodes.KCuSLrGBXunxbKi.geometry} material={materials.ucekphvVRyoLWgE} />
        <mesh geometry={nodes.OuafqOjNBHbOxeM.geometry} material={materials.BCKXYWKgOWAMzzp} />
        <mesh geometry={nodes.onCnMAgiUfYghCa.geometry} material={materials.eFnCMDGzSpQJEdf} />
        <mesh geometry={nodes.DRUMenkquqOqPBB.geometry} material={materials.schaJKIVUmSWLQA} />
        <mesh geometry={nodes.fYsQHZAKKxrBUHu.geometry} material={materials.uhSjoqjjxLxIJEp} />
        <mesh geometry={nodes.bRkfhfzPFhAcloN.geometry} material={materials.xjMjLzeClXxPZiL} />
        <mesh geometry={nodes.iQvheLuzdQkuSeJ.geometry} material={materials.aAXWAJGJAtUuAVC} />
        <mesh geometry={nodes.puLESYTHooXoUCA.geometry} material={materials.pqksKtWbSqRTkqv} />
        <mesh geometry={nodes.XHIStvRRJuEGVeQ.geometry} material={materials.uhSjoqjjxLxIJEp} />
        <mesh geometry={nodes.SxaGKaPygGiLcmN.geometry} material={materials.movFhSaNkSrNKyM} />
        <mesh geometry={nodes.qKXRmmKkymmLTYt.geometry} material={materials.aAXWAJGJAtUuAVC} />
        <mesh geometry={nodes.bJCbNxhrcmEdcCM.geometry} material={materials.cgOiivtAxUoeEfW} />
        <mesh geometry={nodes.BAxMEALGGWqitaP.geometry} material={materials.aAXWAJGJAtUuAVC} />
        <mesh geometry={nodes.HNXdaurOJgVpqwO.geometry} material={materials.uhSjoqjjxLxIJEp} />
        <mesh geometry={nodes.cLqNTiqGrfBAsrs.geometry} material={materials.movFhSaNkSrNKyM} />
        <mesh geometry={nodes.wFzJvNXcWBRHhdQ.geometry} material={materials.xjMjLzeClXxPZiL} />
        <mesh geometry={nodes.DAQxQnEgVbUVChn.geometry} material={materials.aAXWAJGJAtUuAVC} />
        <mesh geometry={nodes.EnVjHvEbvGptqIc.geometry} material={materials.pqksKtWbSqRTkqv} />
        <mesh geometry={nodes.MJokNNForrVoctQ.geometry} material={materials.uhSjoqjjxLxIJEp} />
        <mesh geometry={nodes.uHvofqgpMqlssnA.geometry} material={materials.lMzofmcJBoknbil} />
        <mesh geometry={nodes.dmvkHjlAcBilttn.geometry} material={materials.lMzofmcJBoknbil} />
        <mesh geometry={nodes.UtxqCQdxFKUWTRG.geometry} material={materials.JMJEizFSpcnBLBu} />
        <mesh geometry={nodes.iQgbGlzLYxmnkEJ.geometry} material={materials.lMzofmcJBoknbil} />
        <mesh geometry={nodes.LucfwAzaOiBHGBs.geometry} material={materials.MyWTkmNpPcgwehb} />
        <mesh geometry={nodes.tJsALhsZGYXQBFg.geometry} material={materials.IyRtefachzKUcBb} />
        <mesh geometry={nodes.vjEAQNHpUyNbGVA.geometry} material={materials.dULQkYmOHsuNGwk} />
        <mesh geometry={nodes.iFNIuSzIVSntlTY.geometry} material={materials.kgpBHanvuTGSAYr} />
        <mesh geometry={nodes.IsQUyjZKDNlKKvu.geometry} material={materials.qDOcIjVpElQVnfu} />
        <mesh geometry={nodes.RFwGWThZbNKmLgt.geometry} material={materials.gMuXNdoZqzJLAvR} />
        <mesh geometry={nodes.lWAKZCzBqgMknbU.geometry} material={materials.IyRtefachzKUcBb} />
        <mesh geometry={nodes.VykuVRzGucARcnD.geometry} material={materials.lMzofmcJBoknbil} />
        <mesh geometry={nodes.jNQJlphSrIRrBKf.geometry} material={materials.JMJEizFSpcnBLBu} />
        <mesh geometry={nodes.XXvXucwLAbdmpHX.geometry} material={materials.lMzofmcJBoknbil} />
        <mesh geometry={nodes.aXNMDmcsLKgffRv.geometry} material={materials.MyWTkmNpPcgwehb} />
        <mesh geometry={nodes.nWGkHaZOXZFJZKv.geometry} material={materials.dULQkYmOHsuNGwk} />
        <mesh geometry={nodes.pOJkkptsLytmtVv.geometry} material={materials.kgpBHanvuTGSAYr} />
        <mesh geometry={nodes.xyVfpiYtqUaEsxm.geometry} material={materials.qDOcIjVpElQVnfu} />
        <mesh geometry={nodes.bPmBAuLIgCpxfIo.geometry} material={materials.ILBWplikIEjpQFu} />
        <mesh geometry={nodes.GkNcoDHRYmNOzNo.geometry} material={materials.ILBWplikIEjpQFu} />
        <mesh geometry={nodes.XRIeMaUGHSkJQqD.geometry} material={materials.JEqrlnZSfFxzXyR} />
        <mesh geometry={nodes.BOsOutQtwlhQDkr.geometry} material={materials.axobLmsfiYAnCsP} />
        <mesh geometry={nodes.jrDatUzPyHNlXIy.geometry} material={materials.ANqxLmGmmZDkKZr} />
        <mesh geometry={nodes.yaqXFfePSuyasqv.geometry} material={materials.JFsLNaKevrqxAHS} />
        <mesh geometry={nodes.tyXDSqxGNFRcIOf.geometry} material={materials.JFsLNaKevrqxAHS} />
        <mesh geometry={nodes.TQYwHoYhoHtCqfY.geometry} material={materials.JkJKKnxTIntgQHC} />
        <mesh geometry={nodes.KGTPsmZXiKwUxBA.geometry} material={materials.JFsLNaKevrqxAHS} />
        <mesh geometry={nodes.rFfmCkJAIfvvcoV.geometry} material={materials.JkJKKnxTIntgQHC} />
        <mesh geometry={nodes.kfFsvEDJevOTjOb.geometry} material={materials.CLxgtuDKMkHlfIs} />
        <mesh geometry={nodes.qjsWGaEQfNknQeo.geometry} material={materials.wHLUdvjLSAdAzpD} />
        <mesh geometry={nodes.mgkXJLMmHQwAPUS.geometry} material={materials.QTWCiCCGMSxWgbc} />
        <mesh geometry={nodes.sFjRDkvMUTeoufu.geometry} material={materials.EgczyvedEqzqMFX} />
        <mesh geometry={nodes.GTNgXHvClILzWkZ.geometry} material={materials.wHLUdvjLSAdAzpD} />
        <mesh geometry={nodes.VJHFxSHDwMHWYbD.geometry} material={materials.JFsLNaKevrqxAHS} />
        <mesh geometry={nodes.NFMjtFHlCmDDDye.geometry} material={materials.fwZBQTUFaZPSpvr} />
        <mesh geometry={nodes.HvmhNBkcFNCkETn.geometry} material={materials.fwZBQTUFaZPSpvr} />
        <mesh geometry={nodes.ljQqiMAOjJnstlz.geometry} material={materials.fwZBQTUFaZPSpvr} />
        <mesh geometry={nodes.UfCFTvPHobNYNuw.geometry} material={materials.fwZBQTUFaZPSpvr} />
        <mesh geometry={nodes.RCtkcivgrajBiil.geometry} material={materials.gSPFLmkAjqDsDpN} />
        <mesh geometry={nodes.FtUZpgMrQeBuRwX.geometry} material={materials.JFsLNaKevrqxAHS} />
        <mesh geometry={nodes.CjrSGiCPDxNIlLL.geometry} material={materials.fwZBQTUFaZPSpvr} />
        <mesh geometry={nodes.cSSDqdAfWghogrf.geometry} material={materials.TOXCTGGcpkubhJV} />
        <mesh geometry={nodes.wAlSALURSIywUpI.geometry} material={materials.fwZBQTUFaZPSpvr} />
        <mesh geometry={nodes.huiqOZNSnkdxFNi.geometry} material={materials.hOQFVPUkStlnLZL} />
        <mesh geometry={nodes.MlrGbWjzMhpBLgs.geometry} material={materials.JFsLNaKevrqxAHS} />
        <mesh geometry={nodes.nZNcztTHfduCKSt.geometry} material={materials.rtSfIyWixTDVpUY} />
        <mesh geometry={nodes.lEnYifWpSCJrErk.geometry} material={materials.pQhxnNuPXoHfCWe} />
        <mesh geometry={nodes.izLdmgMAtFNCERj.geometry} material={materials.bxAqWBgABbIjzMY} />
        <mesh geometry={nodes.cSEmYvJalQNIQhs.geometry} material={materials.jsQvjteHecACAeR} />
        <mesh geometry={nodes.YbRoDtvjJInZyJV.geometry} material={materials.pQhxnNuPXoHfCWe} />
        <mesh geometry={nodes.jWuDbHTaFBaDrrZ.geometry} material={materials.bxAqWBgABbIjzMY} />
        <mesh geometry={nodes.FjuCyHASTTcZWMa.geometry} material={materials.jsQvjteHecACAeR} />
        <mesh geometry={nodes.XWpivUINjhZkYcr.geometry} material={materials.QTWCiCCGMSxWgbc} />
        <mesh geometry={nodes.ZfIqyVMdJBwdcCh.geometry} material={materials.QTWCiCCGMSxWgbc} />
        <mesh geometry={nodes.QWWffXFZwcUtXBq.geometry} material={materials.EgczyvedEqzqMFX} />
        <mesh geometry={nodes.nFJQEQmmoUGBnDJ.geometry} material={materials.JFsLNaKevrqxAHS} />
        <mesh geometry={nodes.urVwmigsGssgzve.geometry} material={materials.JFsLNaKevrqxAHS} />
        <mesh geometry={nodes.dxoUetmUtIBIVWe.geometry} material={materials.QTWCiCCGMSxWgbc} />
        <mesh geometry={nodes.giroUgjRKWjGLZl.geometry} material={materials.EgczyvedEqzqMFX} />
        <mesh geometry={nodes.tCtMfEJwdLuvQGF.geometry} material={materials.KEnlbNmQcpvdozb} />
        <mesh geometry={nodes.yAsoSSImdAWHEeb.geometry} material={materials.KEnlbNmQcpvdozb} />
        <mesh geometry={nodes.esWBIEGuqiSJTxI.geometry} material={materials.KEnlbNmQcpvdozb} />
        <mesh geometry={nodes.AoltIyCMGTXxbug.geometry} material={materials.KEnlbNmQcpvdozb} />
        <mesh geometry={nodes.dXHoHaAUioufqIg.geometry} material={materials.ZwfmonZpLDaDbGy} />
        <mesh geometry={nodes.SlAbfqkVZCCQOaf.geometry} material={materials.ZwfmonZpLDaDbGy} />
        <mesh geometry={nodes.qczdsxpvVWujaAs.geometry} material={materials.ZwfmonZpLDaDbGy} />
        <mesh geometry={nodes.HBgvryqiUSEQVsz.geometry} material={materials.ZwfmonZpLDaDbGy} />
        <mesh geometry={nodes.RVbVFOYkEoTWZJR.geometry} material={materials.lciUnRZYuzqSpWr} />
        <mesh geometry={nodes.LqHGbWICfVuDiVa.geometry} material={materials.dvmeoUrdxtrSUKH} />
        <mesh geometry={nodes.evAvupWGSpKoduy.geometry} material={materials.KEnlbNmQcpvdozb} />
        <mesh geometry={nodes.tfoIbGUlplBnnGI.geometry} material={materials.KEnlbNmQcpvdozb} />
        <mesh geometry={nodes.KbIuewYygqAXAOJ.geometry} material={materials.KEnlbNmQcpvdozb} />
        <mesh geometry={nodes.STnvEOzUJTbYYoX.geometry} material={materials.KEnlbNmQcpvdozb} />
        <mesh geometry={nodes.pVZQtUhwcfzpspL.geometry} material={materials.ZwfmonZpLDaDbGy} />
        <mesh geometry={nodes.ISzOYZOQvVfmQYC.geometry} material={materials.ZwfmonZpLDaDbGy} />
        <mesh geometry={nodes.yPLdQhxBlbsTdLZ.geometry} material={materials.ZwfmonZpLDaDbGy} />
        <mesh geometry={nodes.KsxOHCkvAaPsioP.geometry} material={materials.ZwfmonZpLDaDbGy} />
        <mesh geometry={nodes.GZLqLapefOYGUhv.geometry} material={materials.lciUnRZYuzqSpWr} />
        <mesh geometry={nodes.zVTeycOoDBbsgsY.geometry} material={materials.dvmeoUrdxtrSUKH} />
        <mesh geometry={nodes.NzfkbcPdvgFzApF.geometry} material={materials.KEnlbNmQcpvdozb} />
        <mesh geometry={nodes.WnfDwdqJiyacwNu.geometry} material={materials.JFsLNaKevrqxAHS} />
        <mesh geometry={nodes.ulUHXepohBRrBai.geometry} material={materials.fmmGyvGJVnVViXe} />
        <mesh geometry={nodes.bvBVGjqyifVGqeO.geometry} material={materials.OthgPpktWeqGgKp} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/vision.glb')
