import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Sans, Sora } from "next/font/google";
import "./globals.css";
import Header from "@/components/ux/Header";
import { ConversationBarDemo } from "@/components/try/ElevenConversation";

const notoSans = Sora({ variable: '--font-sans' });

const geistSans = Sora({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Sora({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MickeyLabs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={notoSans.variable}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <div className="fixed bottom-3 -right-8  z-50">
          <ConversationBarDemo />
        </div>
      </body>
    </html>
  );
}
